version: 2
updates:
  #Ruby Gems
  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "daily"

  #Bootstrap
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
