title: Sonic X TCG
email: your-email@example.com
description: >-
  Sonic X TCG
baseurl: /SonicXTCG
url: https://raceprouk.github.io
github_username: RaceProUK
twitter_username: RaceProUK

sass:
  style: compressed
